name: Release Package
on:
  release:
    types: [released]
jobs:
  publish:
    name: publish
    environment: release
    if: ${{ github.event.release.target_commitish == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.16.1' # LTS
          registry-url: 'https://registry.npmjs.org'
          scope: '@jucr'
      - run: yarn
      - run: yarn test
      - run: yarn prepare
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
